---
- name: Test nginx syntax
  ansible.builtin.command:
    cmd: nginx -t
  register: nginx_test
  changed_when: false
  failed_when: nginx_test.rc != 0

- name: Restart nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted
